# Increase memory available to Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true
org.gradle.configuration-cache=false

# Fabric Properties
minecraft_version=1.20.1
loader_version=0.19.5
loom_version=1.17-SNAPSHOT
fabric_api_version=0.92.12+1.20.1

# Mod Properties
mod_version=1.1.12.1-fabric+mc1.20.1
maven_group=com.bmt.kaleidoscope_world_liquor
archives_base_name=kaleidoscope_world_liquor

# Dependencies
forgeconfigapiport_version=8.0.3
kaleidoscope_tavern_version=1.2.0.9-fabric+mc1.20.1
kaleidoscope_doll_version=1.0.9
jei_version=15.20.0.132
jade_version=11.13.1+fabric
create_fabric_version=6.0.8.1+build.1744-mc1.20.1
ponder_version=1.0.91
porting_lib_version=2.3.15+1.20.1
