# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# IntelliJ IDEA is not yet fully compatible with configuration cache, see: https://github.com/FabricMC/fabric-loom/issues/1349
org.gradle.configuration-cache=false

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.1.2
loader_version=0.19.3
loom_version=1.17-SNAPSHOT

# Mod Properties
mod_version=1.1.10-fabric+mc26.1.2
maven_group=com.bmt.kaleidoscope_world_liquor
archives_base_name=kaleidoscope_world_liquor

# Dependencies
fabric_api_version=0.155.2+26.1.2
forge_config_api_version=26.1.5
jade_version=26.1.6+fabric
jei_version=26.1.2-fabric:29.16.0.47

pluginManagement {
	repositories {
		maven {
			name = 'Fabric'
			url = 'https://maven.fabricmc.net/'
		}
		mavenCentral()
		gradlePluginPortal()
	}
}
